In [4]:
from sklearn.linear_model import LogisticRegression

  Using cached scikit_learn-1.9.1-cp314-cp314-win_amd64.whl.metadata (9.3 kB)
  Using cached scipy-1.18.1-cp314-cp314-win_amd64.whl.metadata (61 kB)
  Using cached joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Using cached scikit_learn-1.9.1-cp314-cp314-win_amd64.whl (8.4 MB)
Using cached joblib-1.6.0-py3-none-any.whl (306 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Using cached narwhals-2.26.0-py3-none-any.whl (474 kB)
Using cached scipy-1.18.1-cp314-cp314-win_amd64.whl (37.4 MB)

   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   ---------------------------------------- 0/5 [scipy]
   -----------------------

In [5]:
model = LogisticRegression()
print(model)

LogisticRegression()


In [11]:
import numpy as np
from sklearn.linear_model import LogisticRegression

X = np.array([[1], [2], [3], [5], [6], [8]])
y = np.array([0, 0, 0, 1, 1, 1])

model = LogisticRegression()
model.fit(X, y)

print(model.predict_proba([[5]]))
print(model.predict([[5]]))

[[0.26083035 0.73916965]]
[1]


In [13]:
from sklearn.ensemble import RandomForestClassifier 
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X, y)
pred = model.predict([[4]])
print(pred)

[0]


In [14]:
from sklearn.svm import SVC

svm_model = SVC()

svm_model.fit(X, y)

prediction = svm_model.predict([[6]])

print(prediction)

[1]


In [15]:
from sklearn.datasets import load_breast_cancer

data = load_breast_cancer()

X = data.data
y = data.target

print("Features:", X.shape)
print("Target:", y.shape)
print("Classes:", data.target_names)

Features: (569, 30)
Target: (569,)
Classes: ['malignant' 'benign']


In [17]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])
stratify=y

Training samples: 455
Testing samples: 114


In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

# 1. Logistic Regression
lr_model = LogisticRegression(max_iter=5000)
lr_model.fit(X_train, y_train)

# 2. Random Forest
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)
rf_model.fit(X_train, y_train)

# 3. SVM
svm_model = SVC()
svm_model.fit(X_train, y_train)

print("All 3 models trained successfully!")

All 3 models trained successfully!


In [20]:
y_pred_lr = lr_model.predict(X_test)
y_pred_rf = rf_model.predict(X_test)
y_pred_svm = svm_model.predict(X_test)

print("Logistic Regression predictions:", y_pred_lr[:10])
print("Random Forest predictions:", y_pred_rf[:10])
print("SVM predictions:", y_pred_svm[:10])

Logistic Regression predictions: [0 1 0 1 0 1 1 0 0 0]
Random Forest predictions: [0 1 0 0 0 1 1 0 0 0]
SVM predictions: [0 1 1 0 0 1 1 0 0 0]


In [21]:
from sklearn.metrics import accuracy_score

accuracy_lr = accuracy_score(y_test, y_pred_lr)
accuracy_rf = accuracy_score(y_test, y_pred_rf)
accuracy_svm = accuracy_score(y_test, y_pred_svm)

print("Logistic Regression Accuracy:", accuracy_lr)
print("Random Forest Accuracy:", accuracy_rf)
print("SVM Accuracy:", accuracy_svm)

Logistic Regression Accuracy: 0.9649122807017544
Random Forest Accuracy: 0.956140350877193
SVM Accuracy: 0.9298245614035088


In [22]:
from sklearn.metrics import precision_score, recall_score, f1_score

print("Logistic Regression")
print("Precision:", precision_score(y_test, y_pred_lr))
print("Recall:", recall_score(y_test, y_pred_lr))
print("F1:", f1_score(y_test, y_pred_lr))

print("\nRandom Forest")
print("Precision:", precision_score(y_test, y_pred_rf))
print("Recall:", recall_score(y_test, y_pred_rf))
print("F1:", f1_score(y_test, y_pred_rf))

print("\nSVM")
print("Precision:", precision_score(y_test, y_pred_svm))
print("Recall:", recall_score(y_test, y_pred_svm))
print("F1:", f1_score(y_test, y_pred_svm))

Logistic Regression
Precision: 0.9594594594594594
Recall: 0.9861111111111112
F1: 0.9726027397260274

Random Forest
Precision: 0.958904109589041
Recall: 0.9722222222222222
F1: 0.9655172413793104

SVM
Precision: 0.9210526315789473
Recall: 0.9722222222222222
F1: 0.9459459459459459


In [23]:
from sklearn.metrics import confusion_matrix

cm_lr = confusion_matrix(y_test, y_pred_lr)
cm_rf = confusion_matrix(y_test, y_pred_rf)
cm_svm = confusion_matrix(y_test, y_pred_svm)

print("Logistic Regression:")
print(cm_lr)

print("\nRandom Forest:")
print(cm_rf)

print("\nSVM:")
print(cm_svm)

Logistic Regression:
[[39  3]
 [ 1 71]]

Random Forest:
[[39  3]
 [ 2 70]]

SVM:
[[36  6]
 [ 2 70]]


In [24]:
import pandas as pd

results = pd.DataFrame({
    "Model": [
        "Logistic Regression",
        "Random Forest",
        "SVM"
    ],
    "Accuracy": [
        accuracy_lr,
        accuracy_rf,
        accuracy_svm
    ],
    "Precision": [
        precision_score(y_test, y_pred_lr),
        precision_score(y_test, y_pred_rf),
        precision_score(y_test, y_pred_svm)
    ],
    "Recall": [
        recall_score(y_test, y_pred_lr),
        recall_score(y_test, y_pred_rf),
        recall_score(y_test, y_pred_svm)
    ],
    "F1 Score": [
        f1_score(y_test, y_pred_lr),
        f1_score(y_test, y_pred_rf),
        f1_score(y_test, y_pred_svm)
    ]
})

results.round(4)

,Model,Accuracy,Precision,Recall,F1 Score
0,Logistic Regression,0.9649,0.9595,0.9861,0.9726
1,Random Forest,0.9561,0.9589,0.9722,0.9655
2,SVM,0.9298,0.9211,0.9722,0.9459


## Conclusion

In this experiment, Logistic Regression, Random Forest, and SVM were trained and evaluated on the Breast Cancer Wisconsin dataset.

The models were compared using Accuracy, Precision, Recall, F1 Score, and Confusion Matrix.

For this particular train-test split, Logistic Regression achieved the highest values across the evaluated metrics among the three models.

The experiment also showed why multiple evaluation metrics are important instead of relying only on accuracy.